version: "3.8"
services:
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
    env_file:
      - ./back/config/mongo.env
  backend:
    build: ./back
    ports:
      - "5000:80"
    volumes:
      - /app/node_modules
      - ./back:/app
    env_file:
      - ./back/config/dev.env
    depends_on:
      - mongodb

  frontend:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
