version: "3"
services:
  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - /app/node_modules
      - ./back/src:/app/src
    env_file:
      - GMAIL_EMAIL=${GMAIL_PASS}
      - GMAIL_PASS=${GMAIL_PASS}
      - SMS_USER=${SMS_USER}
      - SMS_PASS=${SMS_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - MONGODB_URL=mongodb://localhost:27017/Runschool

  frontend:
    build: ./front
    ports:
      - ${GATEWAY_PORT}:3000
    volumes:
      - ./front/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - api

  nginx:
    restart: always
    build: ./nginx
    ports:
      - 80:80
