version: "3.8"
services:
  # mongodb:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - data:/data/db
  #   env_file:
  #     - ./back/config/mongo.env
  backend:
    build: 
      context: ./back
      dockerfile: Dockerfile.dev
    ports:
      - "5000:3000"
    # volumes:
    #   - /app/node_modules
    #   - ./back/src:/app/src
    env_file:
      - ./back/config/dev.env
    # depends_on:
    #   - mongodb

  frontend:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

# volumes:
#   data:
