version: "3"
services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    ports:
      - "5000:3000"
    volumes:
      - /app/node_modules
      - ./back/src:/app/src
    env_file:
      - ./back/config/dev.env

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./front/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
