name: deploy-container

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "back/**"

defaults:
  run:
    working-directory: back

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: CI=true npm run test
